// <auto-generated />
namespace IBulum_v1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddInvoiceTimeReportandInquiriesControllers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddInvoiceTimeReportandInquiriesControllers));
        
        string IMigrationMetadata.Id
        {
            get { return "201910300909188_Add Invoice,TimeReport and Inquiries Controllers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
